import requests


class Wordlist:
    @property
    def adjectives():
        raise NotImplementedError

    @property
    def nouns():
        raise NotImplementedError


class TestWordlist(Wordlist):
    @property
    def adjectives(self):
        return ["dumb"]

    @property
    def nouns(self):
        return ["test"]


class TurboencabulatorWordlist(Wordlist):

    processed = ""

    @property
    def adjectives(self):
        processed = self.__process__()
        return [
            word["lemma"]
            for sentence in processed["sentences"]
            for word in sentence
            if word["pos"] == "ADJ"
        ]

    @property
    def nouns(self):
        processed = self.__process__()
        return [
            word["lemma"]
            for sentence in processed["sentences"]
            for word in sentence
            if word["pos"] == "NOUN"
        ]

    def __process__(self):
        if not self.processed:
            self.processed = requests.post(
                "https://spacy/api",
                data="""{
                    "text": "For a number of years now, work has has been proceeding in order to bring prefection to the crudely conceived idea of a machine that would work to not only supply inverse reactive current, for use in unilateral phase detectors, but would also be capable of automatically synchronising cardinal grammeters.  Such a machine is the 'Retroencabulator'.  Basically, the only new principle involved is that instead of the power being generated by the relaxive motion of conductors and fluxes, it is produced by the modial interactions of magneto- reluctance and capacitive directance. The original machine had a base-plate of prefabulated amulite, surrounded by a malleable logarithmic casing in such a way that the two spurving bearings were in direct line with the pentametric fan, the latter consisted simply of six hydrocoptic marzelvanes, so fitted to the ambifacient lunar vaneshaft that side fumbling was effectively prevented.  The main winding was of the normal lotus- o-delta type placed in panendermic semiboloid solts in the stator, every seventh conductor being connected by a non-reversible termic pipe to the differential girdlespring on the 'up' end of the grammeter.                    Forty-one manestically placed grouting brushes were arrranged to feed into the rotor slip stream a mixture of high S-value phenyhydrobenzamine and 5 percent reminative tetraiodohexamine.  Both these liquids have specific pericosities given by p=2.4 Cn where n is the diathecial evolute of retrograde temperature phase disposition and C is the Chomondeley's annual grillage coefficient. Initially, n was measured with the aid of a metapolar pilfrometer, but up to the present date nothing has been found to equal the transcetental hopper dadoscope.                    Electrical engineers will appreciate the difficulty of nubbing together a regurgitative purwell and a superaminative wennel-sprocket.  Indeed, this proved to be a stumbling block to further development until, in 1943, it was found that the use of anhydrous nagling pins enabled a kyptonastic boiling shim to be tankered.                The early attempts to construct a sufficiently robust spiral decommutator failed largely because of lack of appreciation of the large quasi-pietic stresses in the gremlin studs; the latter were specially designed to hold the roffit bars to the spamshaft.  When, however, it was discovered that wending could be prevented by the simple addition of teeth to socket, almost perfect running was secured.                    The operating point is maintained as near as possible to the HF rem peak by constantly fromaging the bituminous spandrels.  This is a distinct advance on the standard nivelsheave in that no drammock oil is required after the phase detractors have remissed.                    Undoubtedly, the Retroencabulator has now reached a very high level of technical development.  It has been successfully used for operating nofer trunnions.  In addition, whenever a barescent skor motion is required, it may be employed in conjunction with a drawn reciprocating dingle arm to reduce sinusoidal depleneration.                    "}""",  # noqa(E501)
                headers={"content-type": "application/json"},
            ).json()
        return self.processed


if __name__ == "__main__":
    this_list = TurboencabulatorWordlist()
    print(this_list.adjectives)
    print(this_list.nouns)
